ishml: "https://cdn.jsdelivr.net/gh/bikibird/ishml@0.1.3/src/ishml.js"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  releases:
    output: true
    permalink: /releases/:name:output_ext
  tutorials:
    output: true
    permalink: /tutorials/:name:output_ext
plugins:
  - jekyll-sitemap
disqus: whitewhalestories
warning:
